In [1]:
import pandas as pd

In [2]:
data = r"C:\Users\debas\OneDrive\Desktop\Final Year Project\Main_prj\new ds\crop_recomendation\prev_data.csv"

In [3]:
df = pd.read_csv(data)

In [ ]:
df

,_id,id,year,state_name,state_code,district_name,district_code,crop_name,crop_code,crop_type,season,area,area_unit,production,production_unit,yield,yield_unit
0,9901,9900,1997-1998,West Bengal,19,Bankura,305,Arecanut,507.0,Spices,Whole Year,5.0,Hectare,12.0,Tonnes,2.400,Tonnes/Hectare
1,9902,9901,1997-1998,West Bengal,19,Bankura,305,Arhar/Tur,202.0,Pulses,Whole Year,205.0,Hectare,110.0,Tonnes,0.537,Tonnes/Hectare
2,9903,9902,1997-1998,West Bengal,19,Bankura,305,Bajra,103.0,Cereals,Kharif,162.0,Hectare,73.0,Tonnes,0.451,Tonnes/Hectare
3,9904,9903,1997-1998,West Bengal,19,Bankura,305,Coconut,1006.0,Oilseeds,Whole Year,135.0,Hectare,769900.0,Tonnes,5702.963,Tonnes/Hectare
4,9905,9904,1997-1998,West Bengal,19,Bankura,305,Dry Chillies,502.0,Spices,Whole Year,1325.0,Hectare,1089.0,Tonnes,0.822,Tonnes/Hectare
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16084,455355,455354,2022-2023,West Bengal,19,Uttar Dinajpur,311,Sunflower,1007.0,Oilseeds,Kharif,4.0,Hectare,3.0,Tonnes,0.750,Tonnes/Hectare
16085,455356,455355,2022-2023,West Bengal,19,Uttar Dinajpur,311,Urad,203.0,Pulses,Kharif,1755.0,Hectare,1344.0,Tonnes,0.766,Tonnes/Hectare
16086,455357,455356,2022-2023,West Bengal,19,Uttar Dinajpur,311,Urad,203.0,Pulses,Rabi,847.0,Hectare,809.0,Tonnes,0.955,Tonnes/Hectare
16087,455358,455357,2022-2023,West Bengal,19,Uttar Dinajpur,311,Urad,203.0,Pulses,Total,2602.0,Hectare,2153.0,Tonnes,0.827,Tonnes/Hectare
16088,455359,455358,2022-2023,West Bengal,19,Uttar Dinajpur,311,Wheat,106.0,Cereals,Rabi,19247.0,Hectare,52794.0,Tonnes,2.743,Tonnes/Hectare

In [5]:
df_filtered = df[df['year'].isin(['2021-2022', '2022-2023'])]

In [ ]:
df_filtered

,_id,id,year,state_name,state_code,district_name,district_code,crop_name,crop_code,crop_type,season,area,area_unit,production,production_unit,yield,yield_unit
14807,432870,432869,2021-2022,West Bengal,19,Alipurduar,664,Arhar/Tur,202.0,Pulses,Rabi,408.0,Hectare,642.0,Tonnes,1.574,Tonnes/Hectare
14808,432871,432870,2021-2022,West Bengal,19,Alipurduar,664,Gram,201.0,Pulses,Rabi,181.0,Hectare,215.0,Tonnes,1.188,Tonnes/Hectare
14809,432872,432871,2021-2022,West Bengal,19,Alipurduar,664,Groundnut,1001.0,Oilseeds,Autumn,120.0,Hectare,185.0,Tonnes,1.542,Tonnes/Hectare
14810,432873,432872,2021-2022,West Bengal,19,Alipurduar,664,Groundnut,1001.0,Oilseeds,Rabi,130.0,Hectare,205.0,Tonnes,1.577,Tonnes/Hectare
14811,432874,432873,2021-2022,West Bengal,19,Alipurduar,664,Groundnut,1001.0,Oilseeds,Summer,225.0,Hectare,487.0,Tonnes,2.164,Tonnes/Hectare
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16084,455355,455354,2022-2023,West Bengal,19,Uttar Dinajpur,311,Sunflower,1007.0,Oilseeds,Kharif,4.0,Hectare,3.0,Tonnes,0.750,Tonnes/Hectare
16085,455356,455355,2022-2023,West Bengal,19,Uttar Dinajpur,311,Urad,203.0,Pulses,Kharif,1755.0,Hectare,1344.0,Tonnes,0.766,Tonnes/Hectare
16086,455357,455356,2022-2023,West Bengal,19,Uttar Dinajpur,311,Urad,203.0,Pulses,Rabi,847.0,Hectare,809.0,Tonnes,0.955,Tonnes/Hectare
16087,455358,455357,2022-2023,West Bengal,19,Uttar Dinajpur,311,Urad,203.0,Pulses,Total,2602.0,Hectare,2153.0,Tonnes,0.827,Tonnes/Hectare
16088,455359,455358,2022-2023,West Bengal,19,Uttar Dinajpur,311,Wheat,106.0,Cereals,Rabi,19247.0,Hectare,52794.0,Tonnes,2.743,Tonnes/Hectare

In [7]:
df_filtered["district_name"].unique()

<StringArray>
[       'Alipurduar',           'Bankura',           'Birbhum',
       'Cooch Behar',  'Dakshin Dinajpur',        'Darjeeling',
           'Hooghly',            'Howrah',        'Jalpaiguri',
          'Jhargram',         'Kalimpong',             'Malda',
       'Murshidabad',             'Nadia', 'North 24 Parganas',
 'Paschim Bardhaman', 'Paschim Medinipur',   'Purba Bardhaman',
   'Purba Medinipur',           'Purulia', 'South 24 Parganas',
    'Uttar Dinajpur']
Length: 22, dtype: str

In [9]:
df_filtered["crop_name"].unique()

<StringArray>
[            'Arhar/Tur',                  'Gram',             'Groundnut',
            'Horse-Gram',                  'Jute',               'Khesari',
               'Linseed',                 'Maize',                'Masoor',
                 'Mesta',     'Moong(Green Gram)',            'Niger Seed',
 'Peas & Beans (Pulses)',                'Potato',     'Rapeseed &Mustard',
                  'Rice',               'Sesamum',             'Sugarcane',
                  'Urad',                 'Wheat',              'Sannhamp',
         'Small Millets',             'Sunflower',                'Barley',
   'Other Kharif Pulses',             'Safflower',              'Soyabean',
               'Tobacco',                  'Ragi',                 'Jowar',
     'Other Rabi Pulses',                 'Bajra',          'Cotton(Lint)']
Length: 33, dtype: str

In [10]:
df_filtered.to_csv("filtered__prev_data.csv", index=False)